---
# Default variables for the kafka_broker role

# Kafka version and download URL
kafka_version: "3.4.0"
kafka_scala_version: "2.13"

# System user and group for Kafka
kafka_user: kafka
kafka_group: kafka

# Directory configuration
kafka_home: /opt/kafka
kafka_installation_dir: /opt/kafka/current
kafka_data_dir: /var/lib/kafka
kafka_log_dir: /var/log/kafka

# Java package name
kafka_java_package: openjdk-11-jdk

# Broker configuration
kafka_broker_id: "{{ inventory_hostname | regex_replace('[^0-9]', '') | int }}"
kafka_listen_address: "{{ ansible_host }}"
kafka_port: 9092
kafka_zookeeper_connect: "{% for host in groups['kafka_servers'] %}{{ hostvars[host].ansible_host }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
kafka_auto_create_topics: "true"
kafka_delete_topic_enable: "true"
kafka_num_partitions: 3
kafka_default_replication_factor: "{{ (groups['kafka_servers'] | length) | min(3) }}"
kafka_log_retention_hours: 168
kafka_log_segment_bytes: 1073741824
kafka_log_retention_check_interval_ms: 300000

# ZooKeeper configuration
zookeeper_enabled: true
zookeeper_port: 2181
zookeeper_data_dir: "{{ kafka_data_dir }}/zookeeper"
zookeeper_servers: "{% for host in groups['kafka_servers'] %}server.{{ loop.index }}={{ hostvars[host].ansible_host }}:2888:3888{% if not loop.last %};{% endif %}{% endfor %}"
zookeeper_id: "{{ (groups['kafka_servers'].index(inventory_hostname) + 1) | int }}"

# JVM settings
kafka_heap_opts: "-Xms1G -Xmx1G"
kafka_jvm_performance_opts: "-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80 -XX:+ExplicitGCInvokesConcurrent"

# Security settings
kafka_security_enabled: false
kafka_sasl_enabled: false
kafka_ssl_enabled: false
kafka_ssl_keystore_location: ""
kafka_ssl_keystore_password: ""
kafka_ssl_key_password: ""
kafka_ssl_truststore_location: ""
kafka_ssl_truststore_password: ""
