---
# Handlers for redis_cache role

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

- name: restart redis
  systemd:
    name: redis
    state: restarted
  when: ansible_service_mgr == 'systemd'

- name: restart redis-sentinel
  systemd:
    name: redis-sentinel
    state: restarted
  when: redis_sentinel_enabled | bool and ansible_service_mgr == 'systemd'
