---
# Handlers for jenkins_ci role

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: wait for jenkins
  uri:
    url: "http://localhost:{{ jenkins_http_port }}/login"
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  until: jenkins_service_status is succeeded
  retries: 60
  delay: 5
  changed_when: false
