apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboarding-portal
  namespace: devops-suite
  labels:
    app: onboarding-portal
    tier: ui
    component: portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onboarding-portal
  template:
    metadata:
      labels:
        app: onboarding-portal
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
      - name: onboarding-portal
        image: ${DOCKER_REGISTRY}/onboarding-portal:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 5000
        env:
        - name: GITLAB_URL
          valueFrom:
            configMapKeyRef:
              name: devops-suite-config
              key: gitlab_url
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: devops-suite-secrets
              key: gitlab_token
        - name: NEXUS_URL
          valueFrom:
            configMapKeyRef:
              name: devops-suite-config
              key: nexus_url
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: devops-suite-secrets
              key: onboarding_admin_user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: devops-suite-secrets
              key: onboarding_admin_password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: devops-suite-secrets
              key: onboarding_secret_key
        - name: SECURE_COOKIES
          value: "True"
        - name: DEBUG
          value: "False"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /api/templates
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/templates
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: onboarding-portal
  namespace: devops-suite
  labels:
    app: onboarding-portal
spec:
  selector:
    app: onboarding-portal
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onboarding-portal-ingress
  namespace: devops-suite
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - onboarding.yourdomain.com
    secretName: onboarding-tls
  rules:
  - host: onboarding.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onboarding-portal
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: onboarding-portal-config
  namespace: devops-suite
data:
  settings.json: |
    {
      "default_domain": "yourdomain.com",
      "templates_dir": "/app/templates",
      "static_dir": "/app/static",
      "development_namespace": "apps-dev",
      "production_namespace": "apps-prod",
      "registry_url": "docker.yourdomain.com"
    }
