---
# Default variables for the tuleap_git role

# Domain and URL configuration
tuleap_domain: tuleap.example.com
tuleap_protocol: https
tuleap_port: 443

# Database configuration
tuleap_db_name: tuleap
tuleap_db_user: tuleap
tuleap_db_password: tuleap
tuleap_mysql_root_password: root

# Admin configuration
tuleap_admin_user: admin
tuleap_admin_password: admin
tuleap_admin_email: "admin@example.com"

# Git configuration
tuleap_gitolite_admin_key: ""

# LDAP configuration
tuleap_ldap_enabled: false
tuleap_ldap_server: "ldap://ldap.example.com"
tuleap_ldap_bind_dn: "cn=admin,dc=example,dc=com"
tuleap_ldap_bind_password: "secret"
tuleap_ldap_base_dn: "ou=users,dc=example,dc=com"

# Mail configuration
tuleap_mail_server: "localhost"
tuleap_mail_port: 25
tuleap_mail_use_ssl: false
tuleap_mail_username: ""
tuleap_mail_password: ""

# Plugin configuration
tuleap_plugins:
  - git
  - tracker
  - agiledashboard
  - graphontrackers
  - pullrequest
  - cardwall
  - docman
  - svn
  - hudson

# System configuration
tuleap_sys_user: codendiadm
tuleap_sys_group: codendiadm
tuleap_sys_default_domain: "{{ ansible_fqdn }}"

# SSL configuration
tuleap_ssl_cert_path: "/etc/pki/tls/certs/tuleap.crt"
tuleap_ssl_key_path: "/etc/pki/tls/private/tuleap.key"
tuleap_ssl_generate_self_signed: true
