---
# Default variables for the jenkins_ci role

# Jenkins version and settings
jenkins_http_port: 8080
jenkins_admin_user: admin
jenkins_admin_password: "admin"  # Change this in production or use vault
jenkins_url_prefix: ""

# Security settings
jenkins_security_realm: "jenkins"  # Options: jenkins, ldap, none
jenkins_authorization_strategy: "loggedin"  # Options: loggedin, matrix, project

# CSRF protection
jenkins_csrf_protection_enabled: true

# JNLP settings
jenkins_jnlp_enabled: false
jenkins_jnlp_port: 50000

# Essential plugins to install
jenkins_plugins:
  - git
  - workflow-aggregator
  - pipeline-stage-view
  - blueocean
  - docker-workflow
  - kubernetes
  - credentials
  - ssh-credentials
  - credentials-binding
  - timestamper
  - cloudbees-folder
  - antisamy-markup-formatter
  - build-timeout
  - matrix-auth
  - role-strategy
  - github-integration
  - ws-cleanup
  - ansicolor

# External URL
jenkins_hostname: "jenkins.example.com"
jenkins_https_enabled: false  # Set to true to enable HTTPS

# Agent settings
jenkins_agent_port: 50000
jenkins_agent_protocols:
  - "JNLP4-connect"
  - "Ping"
