---
# Handlers for tuleap_git role

- name: restart tuleap
  systemd:
    name: tuleap
    state: restarted
    daemon_reload: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
