---
# Default variables for the nexus_repo role

# Nexus version and download URL
nexus_version: "3.58.1-02"
nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}.tar.gz"

# System user and group for Nexus
nexus_user: nexus
nexus_group: nexus

# Directory configuration
nexus_home: /opt/nexus
nexus_installation_dir: /opt/nexus/current
nexus_data_dir: /opt/sonatype-work/nexus3
nexus_log_dir: /var/log/nexus

# HTTP settings
nexus_host: "0.0.0.0"
nexus_port: 8081
nexus_context_path: "/"
nexus_domain: "nexus.example.com"

# JVM settings
nexus_jvm_xms: "1200M"
nexus_jvm_xmx: "1200M"
nexus_jvm_max_direct_memory: "2G"
nexus_jvm_additional_options: "-XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/nexus/jvm.log"

# Java package name
nexus_java_package: openjdk-8-jdk

# Admin account
nexus_admin_password: "admin123"
nexus_anonymous_access: false

# SSL configuration
nexus_ssl_enabled: false
nexus_ssl_cert: ""
nexus_ssl_key: ""

# Repository configuration (Note: actual repo config requires scripts)
nexus_delete_default_repos: false
nexus_create_maven_repos: true
nexus_create_docker_repos: true
nexus_create_npm_repos: true
nexus_create_pypi_repos: true
nexus_cleanup_policies_enabled: true

# Backup configuration
nexus_backup_enabled: true
nexus_backup_dir: /opt/nexus/backup
nexus_backup_retention_days: 7

# Monitoring
nexus_monitoring_enabled: true
