---
# Rancher deployment playbook
- name: Deploy Rancher Kubernetes Management
  hosts: rancher_servers
  become: true
  tags:
    - rancher
    - kubernetes
  
  pre_tasks:
    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
    
    - name: Add Docker apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

  roles:
    - rancher_k8s

  post_tasks:
    - name: Configure firewall for HTTP
      ufw:
        rule: allow
        port: 80
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Configure firewall for HTTPS
      ufw:
        rule: allow
        port: 443
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Configure firewall for Kubernetes API
      ufw:
        rule: allow
        port: 6443
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Wait for Rancher to become available
      uri:
        url: https://{{ rancher_domain | default('localhost') }}/
        validate_certs: no
        status_code: 200
        timeout: 5
      register: rancher_startup
      retries: 60
      delay: 10
      until: rancher_startup is success
      changed_when: false
